//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BnanFollowUpContracts
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Cas_User_Validity_Contract
    {
        public string CR_Cas_User_Validity_Contract_User_Id { get; set; }
        public string CR_Cas_User_Validity_Contract_Admin { get; set; }
        public Nullable<bool> CR_Cas_User_Validity_Contract_Register { get; set; }
        public Nullable<bool> CR_Cas_User_Validity_Contract_Chamber_Commerce { get; set; }
        public Nullable<bool> CR_Cas_User_Validity_Contract_Transfer_Permission { get; set; }
        public Nullable<bool> CR_Cas_User_Validity_Contract_Licence_Municipale { get; set; }
        public Nullable<bool> CR_Cas_User_Validity_Contract_Company_Address { get; set; }
        public Nullable<bool> CR_Cas_User_Validity_Contract_Traffic_License { get; set; }
        public Nullable<bool> CR_Cas_User_Validity_Contract_Insurance { get; set; }
        public Nullable<bool> CR_Cas_User_Validity_Contract_Operating_Card { get; set; }
        public Nullable<bool> CR_Cas_User_Validity_Contract_Chkec_Up { get; set; }
        public Nullable<bool> CR_Cas_User_Validity_Contract_Id { get; set; }
        public Nullable<bool> CR_Cas_User_Validity_Contract_Driving_License { get; set; }
        public Nullable<bool> CR_Cas_User_Validity_Contract_Renter_Address { get; set; }
        public Nullable<bool> CR_Cas_User_Validity_Contract_Employer { get; set; }
        public Nullable<bool> CR_Cas_User_Validity_Contract_Tires { get; set; }
        public Nullable<bool> CR_Cas_User_Validity_Contract_Oil { get; set; }
        public Nullable<bool> CR_Cas_User_Validity_Contract_Maintenance { get; set; }
        public Nullable<bool> CR_Cas_User_Validity_Contract_FBrake_Maintenance { get; set; }
        public Nullable<bool> CR_Cas_User_Validity_Contract_BBrake_Maintenance { get; set; }
        public Nullable<bool> CR_Cas_User_Validity_Contract_Extension { get; set; }
        public Nullable<bool> CR_Cas_User_Validity_Contract_Age { get; set; }
        public Nullable<decimal> CR_Cas_User_Validity_Contract_Open_Amout_Rate { get; set; }
        public Nullable<decimal> CR_Cas_User_Validity_Contract_Discount_Rate { get; set; }
        public Nullable<int> CR_Cas_User_Validity_Contract_Km { get; set; }
        public Nullable<int> CR_Cas_User_Validity_Contract_Hour { get; set; }
        public Nullable<bool> CR_Cas_User_Validity_Contract_Cancel { get; set; }
        public Nullable<bool> CR_Cas_User_Validity_Contract_End { get; set; }
        public Nullable<decimal> CR_Cas_User_Validity_Contract_Close { get; set; }
        public Nullable<decimal> CR_Cas_User_Validity_Contract_Close_Amount_Rate { get; set; }
        public string CR_Cas_User_Validity_Contract_Status { get; set; }
        public string CR_Cas_User_Validity_Contract_Reasons { get; set; }
    
        public virtual CR_Cas_User_Information CR_Cas_User_Information { get; set; }
    }
}
