//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BnanFollowUpContracts
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Cas_Sup_Bank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_Cas_Sup_Bank()
        {
            this.CR_Cas_Account_Receipt = new HashSet<CR_Cas_Account_Receipt>();
            this.CR_Cas_Account_Restrictions = new HashSet<CR_Cas_Account_Restrictions>();
            this.CR_Cas_Account_Transfers_Tenants = new HashSet<CR_Cas_Account_Transfers_Tenants>();
            this.CR_Cas_Sup_SalesPoint = new HashSet<CR_Cas_Sup_SalesPoint>();
        }
    
        public string CR_Cas_Sup_Bank_Code { get; set; }
        public string CR_Cas_Sup_Bank_Com_Code { get; set; }
        public string CR_Cas_Sup_Bank_Mas_Code { get; set; }
        public string CR_Cas_Sup_Bank_Account_No { get; set; }
        public string CR_Cas_Sup_Bank_Ar_Name { get; set; }
        public string CR_Cas_Sup_Bank_En_Name { get; set; }
        public string CR_Cas_Sup_Bank_Status { get; set; }
        public string CR_Cas_Sup_Bank_Reasons { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Account_Receipt> CR_Cas_Account_Receipt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Account_Restrictions> CR_Cas_Account_Restrictions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Account_Transfers_Tenants> CR_Cas_Account_Transfers_Tenants { get; set; }
        public virtual CR_Mas_Com_Lessor CR_Mas_Com_Lessor { get; set; }
        public virtual CR_Mas_Sup_Bank CR_Mas_Sup_Bank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Sup_SalesPoint> CR_Cas_Sup_SalesPoint { get; set; }
    }
}
