//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BnanFollowUpContracts
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Cas_Car_Price_Basic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_Cas_Car_Price_Basic()
        {
            this.CR_Cas_Car_Price_Choices = new HashSet<CR_Cas_Car_Price_Choices>();
            this.CR_Cas_Car_Price_Features = new HashSet<CR_Cas_Car_Price_Features>();
            this.CR_Cas_Contract_Basic = new HashSet<CR_Cas_Contract_Basic>();
        }
    
        public string CR_Cas_Car_Price_Basic_No { get; set; }
        public string CR_Cas_Car_Price_Basic_Year { get; set; }
        public string CR_Cas_Car_Price_Basic_Type { get; set; }
        public string CR_Cas_Car_Price_Basic_Lessor_Code { get; set; }
        public string CR_Cas_Car_Price_Basic_Sector { get; set; }
        public string CR_Cas_Car_Price_Basic_Brand_Code { get; set; }
        public string CR_Cas_Car_Price_Basic_Model_Code { get; set; }
        public Nullable<int> CR_Cas_Car_Price_Basic_Car_Year { get; set; }
        public string CR_Cas_Car_Price_Basic_Category_Code { get; set; }
        public Nullable<System.DateTime> CR_Cas_Car_Price_Basic_Date { get; set; }
        public Nullable<System.DateTime> CR_Cas_Car_Price_Basic_Start_Date { get; set; }
        public Nullable<System.DateTime> CR_Cas_Car_Price_Basic_End_Date { get; set; }
        public Nullable<decimal> CR_Cas_Car_Price_Basic_Daily_Rent { get; set; }
        public Nullable<decimal> CR_Cas_Car_Price_Basic_Weekly_Rent { get; set; }
        public Nullable<decimal> CR_Cas_Car_Price_Basic_Monthly_Rent { get; set; }
        public Nullable<decimal> CR_Cas_Car_Price_Basic_Rental_Tax_Rate { get; set; }
        public Nullable<int> CR_Cas_Car_Price_Basic_No_Daily_Free_KM { get; set; }
        public Nullable<decimal> CR_Cas_Car_Price_Basic_Additional_KM_Value { get; set; }
        public Nullable<int> CR_Cas_Car_Price_Basic_No_Free_Additional_Hours { get; set; }
        public Nullable<int> CR_Cas_Car_Price_Basic_Hour_Max { get; set; }
        public Nullable<decimal> CR_Cas_Car_Price_Basic_Extra_Hour_Value { get; set; }
        public Nullable<int> CR_Cas_Car_Price_Basic_Min_Age_Renter { get; set; }
        public Nullable<int> CR_Cas_Car_Price_Basic_Max_Age_Renter { get; set; }
        public Nullable<bool> CR_Cas_Car_Price_Basic_Additional_Driver { get; set; }
        public Nullable<decimal> CR_Cas_Car_Price_Basic_Additional_Driver_Value { get; set; }
        public Nullable<decimal> CR_Cas_Car_Price_Basic_Internal_Fees_Tamm { get; set; }
        public Nullable<decimal> CR_Cas_Car_Price_Basic_International_Fees_Tamm { get; set; }
        public Nullable<bool> CR_Cas_Car_Price_Basic_Does_Require_Financial_Credit { get; set; }
        public Nullable<decimal> CR_Cas_Car_Price_Basic_Min_Percentage_Contract_Value { get; set; }
        public Nullable<decimal> CR_Cas_Car_Price_Basic_Carrying_Accident { get; set; }
        public Nullable<decimal> CR_Cas_Car_Price_Basic_Carrying_Fire { get; set; }
        public Nullable<decimal> CR_Cas_Car_Price_Basic_Stealing { get; set; }
        public Nullable<decimal> CR_Cas_Car_Price_Basic_Drowning { get; set; }
        public Nullable<bool> CR_Cas_Car_Price_Basic_Activation { get; set; }
        public Nullable<System.DateTime> CR_Cas_Car_Price_Basic_About_To_Expire { get; set; }
        public string CR_Cas_Car_Price_Basic_Status { get; set; }
        public string CR_Cas_Car_Price_Basic_Reasons { get; set; }
    
        public virtual CR_Mas_Com_Lessor CR_Mas_Com_Lessor { get; set; }
        public virtual CR_Mas_Sup_Brand CR_Mas_Sup_Brand { get; set; }
        public virtual CR_Mas_Sup_Category CR_Mas_Sup_Category { get; set; }
        public virtual CR_Mas_Sup_Model CR_Mas_Sup_Model { get; set; }
        public virtual CR_Mas_Sup_Sector CR_Mas_Sup_Sector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Car_Price_Choices> CR_Cas_Car_Price_Choices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Car_Price_Features> CR_Cas_Car_Price_Features { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Contract_Basic> CR_Cas_Contract_Basic { get; set; }
    }
}
