//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BnanFollowUpContracts
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Cas_Contract_Virtual_Inspection
    {
        public string CR_Cas_Contract_Virtual_Inspection_No { get; set; }
        public int CR_Cas_Contract_Virtual_Inspection_In_Out { get; set; }
        public int CR_Cas_Contract_Virtual_Inspection_Code { get; set; }
        public Nullable<bool> CR_Cas_Contract_Virtual_Inspection_Action { get; set; }
        public string CR_Cas_Contract_Virtual_Inspection_Remarks { get; set; }
        public string CR_Cas_Contract_Virtual_Inspection_Pic1 { get; set; }
        public string CR_Cas_Contract_Virtual_Inspection_Pic2 { get; set; }
        public string CR_Cas_Contract_Virtual_Inspection_Pic3 { get; set; }
        public string CR_Cas_Contract_Virtual_Inspection_Pic4 { get; set; }
        public string CR_Cas_Contract_Virtual_Inspection_Pic5 { get; set; }
        public string CR_Cas_Contract_Virtual_Inspection_Pic6 { get; set; }
        public string CR_Cas_Contract_Virtual_Inspection_Pic7 { get; set; }
        public string CR_Cas_Contract_Virtual_Inspection_Pic8 { get; set; }
        public string CR_Cas_Contract_Virtual_Inspection_Pic9 { get; set; }
        public string CR_Cas_Contract_Virtual_Inspection_Pic10 { get; set; }
    }
}
