//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BnanFollowUpContracts
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Cas_Contract_Additional
    {
        public string CR_Cas_Contract_Additional_No { get; set; }
        public string CR_Cas_Contract_Additional_Code { get; set; }
        public Nullable<decimal> CR_Cas_Contract_Additional_Value { get; set; }
    }
}
