//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BnanFollowUpContracts
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Cas_Sup_Car_Doc_Mainten
    {
        public string CR_Cas_Sup_Car_Doc_Mainten_Serail_No { get; set; }
        public string CR_Cas_Sup_Car_Doc_Mainten_Code { get; set; }
        public string CR_Cas_Sup_Car_Doc_Mainten_Type { get; set; }
        public string CR_Cas_Sup_Car_Doc_Mainten_Lessor_Code { get; set; }
        public string CR_Cas_Sup_Car_Doc_Mainten_Branch_Code { get; set; }
        public string CR_Cas_Sup_Car_Doc_Mainten_No { get; set; }
        public Nullable<System.DateTime> CR_Cas_Sup_Car_Doc_Mainten_Date { get; set; }
        public Nullable<System.DateTime> CR_Cas_Sup_Car_Doc_Mainten_Start_Date { get; set; }
        public Nullable<System.DateTime> CR_Cas_Sup_Car_Doc_Mainten_End_Date { get; set; }
        public Nullable<bool> CR_Cas_Sup_Car_Doc_Mainten_Activation { get; set; }
        public Nullable<int> CR_Cas_Sup_Car_Doc_Mainten_Limit_KM { get; set; }
        public Nullable<System.DateTime> CR_Cas_Sup_Car_Doc_Mainten_About_To_Expire { get; set; }
        public Nullable<int> CR_Cas_Sup_Car_Doc_Mainten_End_KM { get; set; }
        public Nullable<int> CR_Cas_Sup_Car_Doc_Mainten_Default_KM { get; set; }
        public string CR_Cas_Sup_Car_Doc_Mainten_Procedure_Type { get; set; }
        public string CR_Cas_Sup_Car_Doc_Mainten_Status { get; set; }
        public string CR_Cas_Sup_Car_Doc_Mainten_Branch_Status { get; set; }
        public string CR_Cas_Sup_Car_Doc_Mainten_Owner_Status { get; set; }
    
        public virtual CR_Cas_Sup_Car_Information CR_Cas_Sup_Car_Information { get; set; }
        public virtual CR_Mas_Sup_Procedures CR_Mas_Sup_Procedures { get; set; }
    }
}
