//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BnanFollowUpContracts
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Cas_Contract_Basic
    {
        public string CR_Cas_Contract_Basic_No { get; set; }
        public int CR_Cas_Contract_Basic_Copy { get; set; }
        public Nullable<int> CR_Cas_Contract_Basic_Year { get; set; }
        public Nullable<int> CR_Cas_Contract_Basic_Type { get; set; }
        public string CR_Cas_Contract_Basic_Lessor { get; set; }
        public string CR_Cas_Contract_Basic_Sector { get; set; }
        public string CR_Cas_Contract_Basic_Owner_Branch { get; set; }
        public Nullable<System.DateTime> CR_Cas_Contract_Basic_Date { get; set; }
        public Nullable<System.TimeSpan> CR_Cas_Contract_Basic_Time { get; set; }
        public string CR_Cas_Contract_Basic_Renter_Id { get; set; }
        public Nullable<bool> CR_Cas_Contract_Basic_is_Renter_Driver { get; set; }
        public string CR_Cas_Contract_Basic_Driver_Id { get; set; }
        public Nullable<bool> CR_Cas_Contract_Basic_is_Km_Open { get; set; }
        public string CR_Cas_Contract_Basic_is_Insurance { get; set; }
        public Nullable<bool> CR_Cas_Contract_Basic_is_Receiving_Branch { get; set; }
        public string CR_Cas_Contract_Basic_is_Receiving_Renter { get; set; }
        public string CR_Cas_Contract_Basic_Car_Serail_No { get; set; }
        public Nullable<bool> CR_Cas_Contract_Basic_is_Additional_Driver { get; set; }
        public string CR_Cas_Contract_Basic_Additional_Driver_Id { get; set; }
        public Nullable<System.DateTime> CR_Cas_Contract_Basic_Start_Date { get; set; }
        public Nullable<System.TimeSpan> CR_Cas_Contract_Basic_Start_Time { get; set; }
        public Nullable<System.DateTime> CR_Cas_Contract_Basic_Expected_End_Date { get; set; }
        public Nullable<System.TimeSpan> CR_Cas_Contract_Basic_Expected_End_Time { get; set; }
        public Nullable<int> CR_Cas_Contract_Basic_Expected_Rental_Days { get; set; }
        public Nullable<decimal> CR_Cas_Contract_Basic_Additional_Driver_Value { get; set; }
        public Nullable<decimal> CR_Cas_Contract_Basic_Authorization_Value { get; set; }
        public Nullable<bool> CR_Cas_Contract_Basic_Use_Within_Country { get; set; }
        public Nullable<System.DateTime> CR_Cas_Contract_Basic_End_Authorization { get; set; }
        public string CR_Cas_Contract_BasicAuthorization_Staus { get; set; }
        public string CR_Cas_Contract_BasicAuthorization_No { get; set; }
        public Nullable<decimal> CR_Cas_Contract_Basic_Daily_Rent { get; set; }
        public Nullable<decimal> CR_Cas_Contract_Basic_Weekly_Rent { get; set; }
        public Nullable<decimal> CR_Cas_Contract_Basic_Monthly_Rent { get; set; }
        public Nullable<decimal> CR_Cas_Contract_Basic_CurrentMeters { get; set; }
        public Nullable<decimal> CR_Cas_Contract_Basic_Additional_Value { get; set; }
        public Nullable<decimal> CR_Cas_Contract_Basic_Choices_Value { get; set; }
        public Nullable<decimal> CR_Cas_Contract_Basic_Tax_Rate { get; set; }
        public Nullable<decimal> CR_Cas_Contract_Basic_User_Discount { get; set; }
        public Nullable<int> CR_Cas_Contract_Basic_Daily_Free_KM { get; set; }
        public Nullable<decimal> CR_Cas_Contract_Basic_Additional_KM_Value { get; set; }
        public Nullable<decimal> CR_Cas_Contract_Basic_Free_Additional_Hours { get; set; }
        public Nullable<decimal> CR_Cas_Contract_Basic_Hour_Max { get; set; }
        public Nullable<decimal> CR_Cas_Contract_Basic_Extra_Hour_Value { get; set; }
        public Nullable<decimal> CR_Cas_Contract_Basic_Value { get; set; }
        public Nullable<decimal> CR_Cas_Contract_Basic_Discount_Value { get; set; }
        public Nullable<decimal> CR_Cas_Contract_Basic_After_Discount_Value { get; set; }
        public Nullable<decimal> CR_Cas_Contract_Basic_Tax_Value { get; set; }
        public Nullable<decimal> CR_Cas_Contract_Basic_Net_Value { get; set; }
        public Nullable<decimal> CR_Cas_Contract_Basic_Payed_Value { get; set; }
        public Nullable<decimal> CR_Cas_Contract_Basic_Previous_Balance { get; set; }
        public Nullable<System.DateTime> CR_Cas_Contract_Basic_Hour_DateTime_Alert { get; set; }
        public string CR_Cas_Contract_Basic_Hour_MsgNo { get; set; }
        public Nullable<System.DateTime> CR_Cas_Contract_Basic_Day_DateTime_Alert { get; set; }
        public string CR_Cas_Contract_Basic_Day_MsgNo { get; set; }
        public string CR_Cas_Contract_Basic_EndContract_MsgNo { get; set; }
        public string CR_Cas_Contract_Basic_Alert_Status { get; set; }
        public string CR_Cas_Contract_Basic_Car_Price_Basic_No { get; set; }
        public string CR_Cas_Contract_Basic_Status { get; set; }
        public string CR_Cas_Contract_Basic_Receiving_Branch { get; set; }
        public Nullable<int> CR_Cas_Contract_Basic_Actual_Total_KM { get; set; }
        public Nullable<int> CR_Cas_Contract_Basic_Delivery_Reading_KM { get; set; }
        public Nullable<int> CR_Cas_Contract_Basic_Actual_Additional_Free_KM { get; set; }
        public Nullable<int> CR_Cas_Contract_Basic_Additional_Hours { get; set; }
        public Nullable<decimal> CR_Cas_Contract_Basic_Actual_Extra_KM_Value { get; set; }
        public Nullable<decimal> CR_Cas_Contract_Basic_Actual_Extra_Hour_Value { get; set; }
        public string CR_Cas_Contract_Basic_Contarct_is_Expenses { get; set; }
        public string CR_Cas_Contract_Basic_Contarct_Expenses_Value { get; set; }
        public string CR_Cas_Contract_Basic_Contarct_Expenses_Description { get; set; }
        public string CR_Cas_Contract_Basic_Contarct_is_Compensation { get; set; }
        public string CR_Cas_Contract_Basic_Contarct_Compensation_Value { get; set; }
        public string CR_Cas_Contract_Basic_Contarct_Compensation_Description { get; set; }
        public string CR_Cas_Contract_Basic_Close_Previous_Balance { get; set; }
        public string CR_Cas_Contract_Basic_Contarct_Remaining_Amount { get; set; }
        public string CR_Cas_Contract_Basic_Statistics_Nationalities { get; set; }
        public string CR_Cas_Contract_Basic_Statistics_Country { get; set; }
        public string CR_Cas_Contract_Basic_Statistics_Gender { get; set; }
        public string CR_Cas_Contract_Basic_Statistics_Jobs { get; set; }
        public string CR_Cas_Contract_Basic_Statistics_Regions_Branch { get; set; }
        public string CR_Cas_Contract_Basic_Statistics_City_Branch { get; set; }
        public string CR_Cas_Contract_Basic_Statistics_Regions_Renter { get; set; }
        public string CR_Cas_Contract_Basic_Statistics_City_Renter { get; set; }
        public string CR_Cas_Contract_Basic_Statistics_Brand { get; set; }
        public string CR_Cas_Contract_Basic_Statistics_Model { get; set; }
        public Nullable<int> CR_Cas_Contract_Basic_Statistics_Year { get; set; }
        public string CR_Cas_Contract_Basic_Statistics_Membership_Code { get; set; }
        public Nullable<int> CR_Cas_Contract_Basic_Statistics_Day_No { get; set; }
        public Nullable<int> CR_Cas_Contract_Basic_Statistics_Time_No { get; set; }
        public Nullable<int> CR_Cas_Contract_Basic_Statistics_Day_Count { get; set; }
        public Nullable<int> CR_Cas_Contract_Basic_Statistics_Age_No { get; set; }
        public Nullable<int> CR_Cas_Contract_Basic_Statistics_Value_No { get; set; }
        public Nullable<int> CR_Cas_Contract_Basic_Statistics_KM { get; set; }
        public string CR_Cas_Contract_Basic_CreateContract_Pdf { get; set; }
        public string CR_Cas_Contract_Basic_CloseContract_Pdf { get; set; }
        public string CR_Cas_Contract_Basic_CreateTGA_Pdf { get; set; }
        public string CR_Cas_Contract_Basic_CloseTGA_Pdf { get; set; }
        public string CR_Cas_Contract_Basic_User_Insert { get; set; }
        public string CR_Cas_Contract_Basic_User_Close { get; set; }
    
        public virtual CR_Cas_Car_Price_Basic CR_Cas_Car_Price_Basic { get; set; }
        public virtual CR_Cas_Sup_Car_Information CR_Cas_Sup_Car_Information { get; set; }
        public virtual CR_Mas_Com_Lessor CR_Mas_Com_Lessor { get; set; }
        public virtual CR_Mas_Renter_Information CR_Mas_Renter_Information { get; set; }
        public virtual CR_Mas_Sup_Sector CR_Mas_Sup_Sector { get; set; }
    }
}
