//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BnanFollowUpContracts
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Cas_Sup_Membership_Conditions
    {
        public string CR_Cas_Sup_Membership_Conditions_Code { get; set; }
        public string CR_Cas_Sup_Membership_Conditions_Lessor_Code { get; set; }
        public Nullable<bool> CR_Cas_Sup_Membership_Conditions_Insert { get; set; }
        public Nullable<decimal> CR_Cas_Sup_Membership_Conditions_Amount { get; set; }
        public Nullable<int> CR_Cas_Sup_Membership_Conditions_Link_1 { get; set; }
        public Nullable<int> CR_Cas_Sup_Membership_Conditions_KM { get; set; }
        public Nullable<int> CR_Cas_Sup_Membership_Conditions_Link_2 { get; set; }
        public Nullable<int> CR_Cas_Sup_Membership_Conditions_Contract_No { get; set; }
        public Nullable<bool> CR_Cas_Sup_Membership_Conditions_is_Correcte { get; set; }
        public string CR_Cas_Sup_Membership_Conditions_Insert_Code { get; set; }
        public Nullable<int> CR_Cas_Sup_Membership_Conditions_Insert_No { get; set; }
        public string CR_Cas_Sup_Membership_Conditions_Insert_Group { get; set; }
        public string CR_Cas_Sup_Membership_Conditions_Picture { get; set; }
    
        public virtual CR_Mas_Com_Lessor CR_Mas_Com_Lessor { get; set; }
        public virtual CR_Mas_Sup_Membership CR_Mas_Sup_Membership { get; set; }
    }
}
