//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BnanFollowUpContracts
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Cas_Sup_Branch_Documentation
    {
        public string CR_Cas_Sup_Branch_Documentation_Lessor_Code { get; set; }
        public string CR_Cas_Sup_Branch_Documentation_Branch_Code { get; set; }
        public string CR_Cas_Sup_Branch_Documentation_Code { get; set; }
        public string CR_Cas_Sup_Procedures_Type { get; set; }
        public string CR_Cas_Sup_Branch_Documentation_No { get; set; }
        public Nullable<System.DateTime> CR_Cas_Sup_Branch_Documentation_Date { get; set; }
        public Nullable<System.DateTime> CR_Cas_Sup_Branch_Documentation_Start_Date { get; set; }
        public Nullable<System.DateTime> CR_Cas_Sup_Branch_Documentation_End_Date { get; set; }
        public Nullable<bool> CR_Cas_Sup_Branch_Documentation_Activation { get; set; }
        public Nullable<decimal> CR_Cas_Sup_Branch_Documentation_Credit_Limit { get; set; }
        public Nullable<System.DateTime> CR_Cas_Sup_Branch_Documentation_About_To_Expire { get; set; }
        public string CR_Cas_Sup_Branch_Documentation_Status { get; set; }
        public string CR_Cas_Sup_Branch_Status { get; set; }
        public string CR_Cas_Sup_Owners_Status { get; set; }
    
        public virtual CR_Cas_Sup_Branch CR_Cas_Sup_Branch { get; set; }
        public virtual CR_Mas_Sup_Procedures CR_Mas_Sup_Procedures { get; set; }
    }
}
