//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BnanFollowUpContracts
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sup_Membership_Group
    {
        public string CR_Mas_Sup_Membership_Group_Code { get; set; }
        public string CR_Mas_Sup_Membership_Group_Id { get; set; }
        public string CR_Mas_Sup_Membership_Stetment { get; set; }
    }
}
