//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BnanFollowUpContracts
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sup_Brand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_Mas_Sup_Brand()
        {
            this.CR_Cas_Car_Price_Basic = new HashSet<CR_Cas_Car_Price_Basic>();
            this.CR_Cas_Sup_Car_Information = new HashSet<CR_Cas_Sup_Car_Information>();
            this.CR_Mas_Sup_Model = new HashSet<CR_Mas_Sup_Model>();
        }
    
        public string CR_Mas_Sup_Brand_Code { get; set; }
        public string CR_Mas_Sup_Brand_Ar_Name { get; set; }
        public string CR_Mas_Sup_Brand_En_Name { get; set; }
        public string CR_Mas_Sup_Brand_Fr_Name { get; set; }
        public string CR_Mas_Sup_Brand_Status { get; set; }
        public string CR_Mas_Sup_Brand_Reasons { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Car_Price_Basic> CR_Cas_Car_Price_Basic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Sup_Car_Information> CR_Cas_Sup_Car_Information { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Mas_Sup_Model> CR_Mas_Sup_Model { get; set; }
    }
}
