//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BnanFollowUpContracts
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Account_Data_Owed
    {
        public string CR_Mas_Account_Data_Owed_Contract_No { get; set; }
        public int CR_Mas_Account_Data_Owed_Counter { get; set; }
        public string CR_Mas_Account_Data_Owed_Com_Code { get; set; }
        public string CR_Mas_Account_Data_Owed_Brn_Code { get; set; }
        public Nullable<decimal> CR_Mas_Account_Data_Owed_Value { get; set; }
        public Nullable<System.DateTime> CR_Mas_Account_Data_Owed_Due_Date { get; set; }
        public Nullable<bool> CR_Mas_Account_Data_Owed_Is_Paid { get; set; }
        public Nullable<System.DateTime> CR_Mas_Account_Data_Owed_Pay_Date { get; set; }
        public string CR_Mas_Account_Data_Owed_Pay_No { get; set; }
        public string CR_Mas_Account_Data_Owed_Contract_Code { get; set; }
    
        public virtual CR_Cas_Sup_Branch CR_Cas_Sup_Branch { get; set; }
    }
}
