//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BnanFollowUpContracts
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sup_Service_Fee_Tamm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_Mas_Sup_Service_Fee_Tamm()
        {
            this.CR_Mas_Service_Tamm_Contract = new HashSet<CR_Mas_Service_Tamm_Contract>();
        }
    
        public string CR_Mas_Sup_Service_Fee_Tamm_Code { get; set; }
        public string CR_Mas_Sup_Service_Fee_Tamm_Ar_Name { get; set; }
        public string CR_Mas_Sup_Service_Fee_Tamm_En_Name { get; set; }
        public string CR_Mas_Sup_Service_Fee_Tamm_Fr_Name { get; set; }
        public Nullable<decimal> CR_Mas_Sup_Service_Fee_Tamm_Value { get; set; }
        public string CR_Mas_Sup_Service_Fee_Tamm_Status { get; set; }
        public string CR_Mas_Sup_Service_Fee_Tamm_Reasons { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Mas_Service_Tamm_Contract> CR_Mas_Service_Tamm_Contract { get; set; }
    }
}
