//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BnanFollowUpContracts
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sup_Educational_Qualification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_Mas_Sup_Educational_Qualification()
        {
            this.CR_Mas_Renter_Information = new HashSet<CR_Mas_Renter_Information>();
        }
    
        public string CR_Mas_Sup_Educational_Qualification_Code { get; set; }
        public string CR_Mas_Sup_Educational_Qualification_Group_Code { get; set; }
        public string CR_Mas_Sup_Educational_Qualification_Ar_Name { get; set; }
        public string CR_Mas_Sup_Educational_Qualification_En_Name { get; set; }
        public string CR_Mas_Sup_Educational_Qualification_Fr_Name { get; set; }
        public string CR_Mas_Sup_Educational_Qualification_Status { get; set; }
        public string CR_Mas_Sup_Educational_Qualification_Reasons { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Mas_Renter_Information> CR_Mas_Renter_Information { get; set; }
        public virtual CR_Mas_Sup_Group CR_Mas_Sup_Group { get; set; }
    }
}
