//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BnanFollowUpContracts
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sup_Choices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_Mas_Sup_Choices()
        {
            this.CR_Cas_Car_Price_Choices = new HashSet<CR_Cas_Car_Price_Choices>();
        }
    
        public string CR_Mas_Sup_Choices_Code { get; set; }
        public string CR_Mas_Sup_Choices_Group_Code { get; set; }
        public string CR_Mas_Sup_Choices_Ar_Name { get; set; }
        public string CR_Mas_Sup_Choices_En_Name { get; set; }
        public string CR_Mas_Sup_Choices_Fr_Name { get; set; }
        public string CR_Mas_Sup_Choices_Status { get; set; }
        public string CR_Mas_Sup_Choices_Reasons { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Car_Price_Choices> CR_Cas_Car_Price_Choices { get; set; }
        public virtual CR_Mas_Sup_Group CR_Mas_Sup_Group { get; set; }
    }
}
