//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BnanFollowUpContracts
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sup_Virtual_Inspection
    {
        public string CR_Mas_Sup_Virtual_Inspection_Code { get; set; }
        public string CR_Mas_Sup_Virtual_Inspection_Type { get; set; }
        public string CR_Mas_Sup_Virtual_Inspection_Ar_Name { get; set; }
        public string CR_Mas_Sup_Virtual_Inspection_En_Name { get; set; }
        public string CR_Mas_Sup_Virtual_Inspection_Fr_Name { get; set; }
        public string CR_Mas_Sup_Virtual_Inspection_Status { get; set; }
        public string CR_Mas_Sup_Virtual_Inspection_Reasons { get; set; }
    }
}
