//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Cas_Account_Receipt
    {
        public string CR_Cas_Account_Receipt_No { get; set; }
        public string CR_Cas_Account_Receipt_Year { get; set; }
        public string CR_Cas_Account_Receipt_Type { get; set; }
        public string CR_Cas_Account_Receipt_Lessor_Code { get; set; }
        public string CR_Cas_Account_Receipt_Branch_Code { get; set; }
        public Nullable<System.DateTime> CR_Cas_Account_Receipt_Date { get; set; }
        public string CR_Cas_Account_Receipt_Contract_Operation { get; set; }
        public string CR_Cas_Account_Receipt_Reference_Type { get; set; }
        public Nullable<decimal> CR_Cas_Account_Receipt_Payment { get; set; }
        public Nullable<decimal> CR_Cas_Account_Receipt_Receipt { get; set; }
        public string CR_Cas_Account_Receipt_Payment_Method { get; set; }
        public string CR_Cas_Account_Receipt_Bank_Code { get; set; }
        public string CR_Cas_Account_Receipt_SalesPoint_No { get; set; }
        public Nullable<decimal> CR_Cas_Account_Receipt_SalesPoint_Previous_Balance { get; set; }
        public string CR_Cas_Account_Receipt_Renter_Code { get; set; }
        public Nullable<decimal> CR_Cas_Account_Receipt_Renter_Previous_Balance { get; set; }
        public string CR_Cas_Account_Receipt_User_Code { get; set; }
        public Nullable<decimal> CR_Cas_Account_Receipt_User_Previous_Balance { get; set; }
        public string CR_Cas_Account_Receipt_Car_Code { get; set; }
        public string CR_Cas_Account_Receipt_Is_Passing { get; set; }
        public Nullable<System.DateTime> CR_Cas_Account_Receipt_Passing_Date { get; set; }
        public string CR_Cas_Account_Receipt_User_Passing { get; set; }
        public string CR_Cas_Account_Receipt_Reference_Passing { get; set; }
        public string CR_Cas_Account_Receipt_Status { get; set; }
        public string CR_Cas_Account_Receipt_Reasons { get; set; }
    
        public virtual CR_Cas_Renter_Lessor CR_Cas_Renter_Lessor { get; set; }
        public virtual CR_Cas_Sup_Bank CR_Cas_Sup_Bank { get; set; }
        public virtual CR_Cas_Sup_Branch CR_Cas_Sup_Branch { get; set; }
        public virtual CR_Cas_Sup_Car_Information CR_Cas_Sup_Car_Information { get; set; }
        public virtual CR_Cas_Sup_SalesPoint CR_Cas_Sup_SalesPoint { get; set; }
        public virtual CR_Cas_User_Information CR_Cas_User_Information { get; set; }
        public virtual CR_Mas_Sup_Payment_Method CR_Mas_Sup_Payment_Method { get; set; }
    }
}
