//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Cas_Sup_Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_Cas_Sup_Branch()
        {
            this.CR_Cas_Account_Bnan_Owed = new HashSet<CR_Cas_Account_Bnan_Owed>();
            this.CR_Cas_Account_Receipt = new HashSet<CR_Cas_Account_Receipt>();
            this.CR_Cas_Account_TAMM_Owed = new HashSet<CR_Cas_Account_TAMM_Owed>();
            this.CR_Cas_Account_Tax_Owed = new HashSet<CR_Cas_Account_Tax_Owed>();
            this.CR_Cas_Account_Tga_Owed = new HashSet<CR_Cas_Account_Tga_Owed>();
            this.CR_Cas_Sup_Branch_Documentation = new HashSet<CR_Cas_Sup_Branch_Documentation>();
            this.CR_Cas_Sup_Car_Information = new HashSet<CR_Cas_Sup_Car_Information>();
            this.CR_Cas_Sup_Main_Brn_Account = new HashSet<CR_Cas_Sup_Main_Brn_Account>();
            this.CR_Cas_Sup_SalesPoint = new HashSet<CR_Cas_Sup_SalesPoint>();
            this.CR_Cas_Sup_Sub_Brn_Account = new HashSet<CR_Cas_Sup_Sub_Brn_Account>();
            this.CR_Mas_Account_Data_Owed = new HashSet<CR_Mas_Account_Data_Owed>();
            this.CR_Mas_Account_License_Owed = new HashSet<CR_Mas_Account_License_Owed>();
            this.CR_Mas_Account_Msg_Owed = new HashSet<CR_Mas_Account_Msg_Owed>();
            this.CR_Mas_Account_Post_Owed = new HashSet<CR_Mas_Account_Post_Owed>();
        }
    
        public string CR_Cas_Sup_Lessor_Code { get; set; }
        public string CR_Cas_Sup_Branch_Code { get; set; }
        public string CR_Cas_Sup_Branch_Ar_Name { get; set; }
        public string CR_Cas_Sup_Branch_Ar_Short_Name { get; set; }
        public string CR_Cas_Sup_Branch_En_Name { get; set; }
        public string CR_Cas_Sup_Branch_En_Short_Name { get; set; }
        public string CR_Cas_Sup_Branch_Fr_Name { get; set; }
        public string CR_Cas_Sup_Branch_Fr_Short_Name { get; set; }
        public string CR_Cas_Sup_Branch_Commercial_Registration_No { get; set; }
        public string CR_Cas_Sup_Branch_Government_No { get; set; }
        public string CR_Cas_Sup_Branch_Tax_No { get; set; }
        public string CR_Cas_Sup_Branch_Tel { get; set; }
        public string CR_Cas_Sup_Branch_Mobile { get; set; }
        public string CR_Cas_Sup_Branch_Stamp { get; set; }
        public string CR_Cas_Sup_Branch_Signature_Director { get; set; }
        public string CR_Cas_Sup_Branch_Signature_Ar_Director_Name { get; set; }
        public string CR_Cas_Sup_Branch_Signature_En_Director_Name { get; set; }
        public string CR_Cas_Sup_Branch_Signature_Fr_Director_Name { get; set; }
        public Nullable<int> CR_Cas_Sup_Branch_Start_Day { get; set; }
        public Nullable<int> CR_Cas_Sup_Branch_End_Day { get; set; }
        public Nullable<System.TimeSpan> CR_Cas_Sup_Branch_Duration_One_Start_Time { get; set; }
        public Nullable<System.TimeSpan> CR_Cas_Sup_Branch_Duration_One_End_Time { get; set; }
        public Nullable<System.TimeSpan> CR_Cas_Sup_Branch_Duration_Tow_Start_Time { get; set; }
        public Nullable<System.TimeSpan> CR_Cas_Sup_Branch_Duration_Tow_End_Time { get; set; }
        public Nullable<System.TimeSpan> CR_Cas_Sup_Branch_Duration_Three_Start_Time { get; set; }
        public Nullable<System.TimeSpan> CR_Cas_Sup_Branch_Duration_Three_End_Time { get; set; }
        public string CR_Cas_Sup_Branch_LogoMap { get; set; }
        public string CR_Cas_Sup_Branch_Status { get; set; }
        public string CR_Cas_Sup_Branch_Reasons { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Account_Bnan_Owed> CR_Cas_Account_Bnan_Owed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Account_Receipt> CR_Cas_Account_Receipt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Account_TAMM_Owed> CR_Cas_Account_TAMM_Owed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Account_Tax_Owed> CR_Cas_Account_Tax_Owed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Account_Tga_Owed> CR_Cas_Account_Tga_Owed { get; set; }
        public virtual CR_Mas_Com_Lessor CR_Mas_Com_Lessor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Sup_Branch_Documentation> CR_Cas_Sup_Branch_Documentation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Sup_Car_Information> CR_Cas_Sup_Car_Information { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Sup_Main_Brn_Account> CR_Cas_Sup_Main_Brn_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Sup_SalesPoint> CR_Cas_Sup_SalesPoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Sup_Sub_Brn_Account> CR_Cas_Sup_Sub_Brn_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Mas_Account_Data_Owed> CR_Mas_Account_Data_Owed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Mas_Account_License_Owed> CR_Mas_Account_License_Owed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Mas_Account_Msg_Owed> CR_Mas_Account_Msg_Owed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Mas_Account_Post_Owed> CR_Mas_Account_Post_Owed { get; set; }
    }
}
