//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Cas_Sup_SalesPoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_Cas_Sup_SalesPoint()
        {
            this.CR_Cas_Account_Receipt = new HashSet<CR_Cas_Account_Receipt>();
        }
    
        public string CR_Cas_Sup_SalesPoint_Code { get; set; }
        public string CR_Cas_Sup_SalesPoint_Com_Code { get; set; }
        public string CR_Cas_Sup_SalesPoint_Brn_Code { get; set; }
        public string CR_Cas_Sup_SalesPoint_Bank_Code { get; set; }
        public string CR_Cas_Sup_SalesPoint_Bank_No { get; set; }
        public string CR_Cas_Sup_SalesPoint_Ar_Name { get; set; }
        public string CR_Cas_Sup_SalesPoint_En_Name { get; set; }
        public Nullable<decimal> CR_Cas_Sup_SalesPoint_Balance { get; set; }
        public string CR_Cas_Sup_SalesPoint_Status { get; set; }
        public string CR_Cas_Sup_SalesPoint_Reasons { get; set; }
        public string CR_Cas_Sup_SalesPoint_Branch_Status { get; set; }
        public string CR_Cas_Sup_SalesPoint_Account_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Account_Receipt> CR_Cas_Account_Receipt { get; set; }
        public virtual CR_Cas_Sup_Bank CR_Cas_Sup_Bank { get; set; }
        public virtual CR_Cas_Sup_Branch CR_Cas_Sup_Branch { get; set; }
        public virtual CR_Mas_Com_Lessor CR_Mas_Com_Lessor { get; set; }
    }
}
