//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Cas_Account_Transfers_Tenants
    {
        public string CR_Cas_Account_Transfers_Tenants_No { get; set; }
        public string CR_Cas_Account_Transfers_Tenants_Year { get; set; }
        public string CR_Cas_Account_Transfers_Tenants_Type { get; set; }
        public string CR_Cas_Account_Transfers_Tenants_Com_Code { get; set; }
        public Nullable<System.DateTime> CR_Cas_Account_Transfers_Tenants_Date { get; set; }
        public string CR_Cas_Account_Transfers_Tenants_Renter_Code { get; set; }
        public Nullable<decimal> CR_Cas_Account_Transfers_Tenants_Amount { get; set; }
        public string CR_Cas_Account_Transfers_Tenants_Payment_Method { get; set; }
        public string CR_Cas_Account_Transfers_Tenants_Bank_Code { get; set; }
        public string CR_Cas_Account_Transfers_Tenants_Transaction_No { get; set; }
        public string CR_Cas_Account_Transfers_Tenants_Status { get; set; }
        public string CR_Cas_Account_Transfers_Tenants_Reasons { get; set; }
    
        public virtual CR_Cas_Renter_Lessor CR_Cas_Renter_Lessor { get; set; }
        public virtual CR_Cas_Sup_Bank CR_Cas_Sup_Bank { get; set; }
        public virtual CR_Mas_Com_Lessor CR_Mas_Com_Lessor { get; set; }
    }
}
