//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Cas_Company_Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_Cas_Company_Contract()
        {
            this.CR_Mas_Service_Tamm_Contract = new HashSet<CR_Mas_Service_Tamm_Contract>();
        }
    
        public string CR_Cas_Company_Contract_No { get; set; }
        public string CR_Cas_Company_Contract_Year { get; set; }
        public string CR_Cas_Company_Contract_Sector { get; set; }
        public string CR_Cas_Company_Contract_Code { get; set; }
        public string CR_Cas_Company_Contract_Lessor { get; set; }
        public string CR_Cas_Company_Contract_Number { get; set; }
        public Nullable<System.DateTime> CR_Cas_Company_Contract_Date { get; set; }
        public Nullable<System.DateTime> CR_Cas_Company_Contract_Start_Date { get; set; }
        public Nullable<System.DateTime> CR_Cas_Company_Contract_End_Date { get; set; }
        public Nullable<bool> CR_Cas_Company_Contract_Activation { get; set; }
        public Nullable<System.DateTime> CR_Cas_Company_Contract_About_To_Expire { get; set; }
        public Nullable<decimal> CR_Cas_Company_Contract_Annual_Fees { get; set; }
        public Nullable<decimal> CR_Cas_Company_Contract_Service_Fees { get; set; }
        public Nullable<decimal> CR_Cas_Company_Contract_Discount_Rate { get; set; }
        public Nullable<decimal> CR_Cas_Company_Contract_Tax_Rate { get; set; }
        public string CR_Cas_Company_Contract_Tamm_User_Id { get; set; }
        public string CR_Cas_Company_Contract_Tamm_User_Password { get; set; }
        public string CR_Cas_Company_Contract_Status { get; set; }
        public string CR_Cas_Company_Contract_Reasons { get; set; }
    
        public virtual CR_Mas_Com_Lessor CR_Mas_Com_Lessor { get; set; }
        public virtual CR_Mas_Sup_Procedures CR_Mas_Sup_Procedures { get; set; }
        public virtual CR_Mas_Sup_Sector CR_Mas_Sup_Sector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Mas_Service_Tamm_Contract> CR_Mas_Service_Tamm_Contract { get; set; }
    }
}
