//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Cas_Basic_Tamm_Contract
    {
        public string CR_Cas_Basic_Tamm_Contract_No { get; set; }
        public Nullable<int> CR_Cas_Basic_Tamm_Contract_Year { get; set; }
        public Nullable<int> CR_Cas_Basic_Tamm_Com_Code { get; set; }
        public Nullable<System.DateTime> CR_Cas_Basic_Tamm_Contract_Date { get; set; }
        public Nullable<System.DateTime> CR_Cas_Basic_Tamm_Contract_Start_Date { get; set; }
        public Nullable<System.DateTime> CR_Cas_Basic_Tamm_Contract_End_Date { get; set; }
        public Nullable<decimal> CR_Cas_Basic_Tamm_Contract_Annual_Fees { get; set; }
        public string CR_Cas_Basic_Tamm_Contract_User_Id { get; set; }
        public string CR_Cas_Basic_Tamm_Contract_User_PassWord { get; set; }
        public Nullable<decimal> CR_Cas_Basic_Tamm_Contract_Tax_Rate { get; set; }
        public string CR_Cas_Basic_Tamm_Contract_Status { get; set; }
        public string CR_Cas_Basic_Tamm_Contract_Reasons { get; set; }
    }
}
