//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Cas_Account_Pay_Owed
    {
        public string CR_Cas_Account_Pay_Owed_No { get; set; }
        public string CR_Cas_Account_Pay_Owed_Year { get; set; }
        public string CR_Cas_Account_Pay_Owed_Type { get; set; }
        public string CR_Cas_Account_Pay_Owed_Com_Code { get; set; }
        public Nullable<System.DateTime> CR_Cas_Account_Pay_Owed_Date { get; set; }
        public Nullable<System.DateTime> CR_Cas_Account_Pay_Owed_From_Date { get; set; }
        public Nullable<System.DateTime> CR_Cas_Account_Pay_Owed_To_Date { get; set; }
        public Nullable<decimal> CR_Cas_Account_Pay_Owed_Amount { get; set; }
        public string CR_Cas_Account_Pay_Owed_Status { get; set; }
        public string CR_Cas_Account_Pay_Owed_Reasons { get; set; }
    
        public virtual CR_Mas_Com_Lessor CR_Mas_Com_Lessor { get; set; }
    }
}
