//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Cas_Account_Restrictions
    {
        public string CR_Cas_Account_Restrictions_No { get; set; }
        public string CR_Cas_Account_Restrictions_Year { get; set; }
        public string CR_Cas_Account_Restrictions_Type { get; set; }
        public string CR_Cas_Account_Restrictions_Lessor { get; set; }
        public string CR_Cas_Account_Restrictions_Branch { get; set; }
        public Nullable<System.DateTime> CR_Cas_Account_Restrictions_Date { get; set; }
        public string CR_Cas_Account_Restrictions_Contract_Operation { get; set; }
        public Nullable<decimal> CR_Cas_Account_Restrictions_Credit { get; set; }
        public Nullable<decimal> CR_Cas_Account_Restrictions_Debit { get; set; }
        public string CR_Cas_Account_Restrictions_Renter { get; set; }
        public string CR_Cas_Account_Restrictions_Car { get; set; }
        public string CR_Cas_Account_Restrictions_User { get; set; }
        public string CR_Cas_Account_Restrictions_Payment_Method { get; set; }
        public string CR_Cas_Account_Restrictions_Bank_Code { get; set; }
        public string CR_Cas_Account_Restrictions_SalesPoint_No { get; set; }
        public string CR_Cas_Account_Restrictions_Voucher { get; set; }
        public string CR_Cas_Account_Restrictions_Main_Com_Account_Code { get; set; }
        public Nullable<decimal> CR_Cas_Account_Restrictions_Main_Com_Account_Balance { get; set; }
        public string CR_Cas_Account_Restrictions_Sub_Com_Account_Code { get; set; }
        public Nullable<decimal> CR_Cas_Account_Restrictions_Sub_Com_Account_Balance { get; set; }
        public string CR_Cas_Account_Restrictions_Main_Brn_Account_Code { get; set; }
        public Nullable<decimal> CR_Cas_Account_Restrictions_Main_Brn_Account_Balance { get; set; }
        public string CR_Cas_Account_Restrictions_Sub_Brn_Account_Code { get; set; }
        public Nullable<decimal> CR_Cas_Account_Restrictions_Sub_Brn_Account_Balance { get; set; }
        public string CR_Cas_Account_Restrictions_Status { get; set; }
        public string CR_Cas_Account_Restrictions_Reasons { get; set; }
    
        public virtual CR_Cas_Renter_Lessor CR_Cas_Renter_Lessor { get; set; }
        public virtual CR_Cas_Sup_Bank CR_Cas_Sup_Bank { get; set; }
        public virtual CR_Cas_Sup_Car_Information CR_Cas_Sup_Car_Information { get; set; }
        public virtual CR_Cas_Sup_Main_Brn_Account CR_Cas_Sup_Main_Brn_Account { get; set; }
        public virtual CR_Cas_Sup_Main_Com_Account CR_Cas_Sup_Main_Com_Account { get; set; }
        public virtual CR_Cas_Sup_Sub_Brn_Account CR_Cas_Sup_Sub_Brn_Account { get; set; }
        public virtual CR_Cas_Sup_Sub_Com_Account CR_Cas_Sup_Sub_Com_Account { get; set; }
        public virtual CR_Cas_User_Information CR_Cas_User_Information { get; set; }
    }
}
