//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Cas_Administrative_Procedures
    {
        public string CR_Cas_Administrative_Procedures_No { get; set; }
        public Nullable<System.DateTime> CR_Cas_Administrative_Procedures_Date { get; set; }
        public Nullable<System.TimeSpan> CR_Cas_Administrative_Procedures_Time { get; set; }
        public string CR_Cas_Administrative_Procedures_Year { get; set; }
        public string CR_Cas_Administrative_Procedures_Sector { get; set; }
        public string CR_Cas_Administrative_Procedures_Code { get; set; }
        public Nullable<int> CR_Cas_Administrative_Int_Procedures_Code { get; set; }
        public string CR_Cas_Administrative_Procedures_Lessor { get; set; }
        public string CR_Cas_Administrative_Procedures_Targeted_Action { get; set; }
        public string CR_Cas_Administrative_Procedures_Com_Supporting { get; set; }
        public Nullable<decimal> CR_Cas_Administrative_Procedures_Value { get; set; }
        public string CR_Cas_Administrative_Procedures_Doc_No { get; set; }
        public Nullable<System.DateTime> CR_Cas_Administrative_Procedures_Doc_Date { get; set; }
        public Nullable<System.DateTime> CR_Cas_Administrative_Procedures_Doc_Start_Date { get; set; }
        public Nullable<System.DateTime> CR_Cas_Administrative_Procedures_Doc_End_Date { get; set; }
        public string CR_Cas_Administrative_Procedures_From_Branch { get; set; }
        public string CR_Cas_Administrative_Procedures_To_Branch { get; set; }
        public Nullable<bool> CR_Cas_Administrative_Procedures_Action { get; set; }
        public string CR_Cas_Administrative_Procedures_User_Insert { get; set; }
        public string CR_Cas_Administrative_Procedures_Type { get; set; }
        public string CR_Cas_Administrative_Procedures_Reasons { get; set; }
    }
}
