//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Cas_User_Information
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_Cas_User_Information()
        {
            this.CR_Cas_Account_Receipt = new HashSet<CR_Cas_Account_Receipt>();
            this.CR_Cas_Account_Restrictions = new HashSet<CR_Cas_Account_Restrictions>();
            this.CR_Cas_User_Branch_Validity = new HashSet<CR_Cas_User_Branch_Validity>();
        }
    
        public string CR_Cas_User_Information_Id { get; set; }
        public string CR_Cas_User_Information_PassWord { get; set; }
        public string CR_Cas_User_Information_Lessor_Code { get; set; }
        public Nullable<bool> CR_Cas_User_Information_Auth_Branch { get; set; }
        public Nullable<bool> CR_Cas_User_Information_Auth_System { get; set; }
        public Nullable<bool> CR_Cas_User_Information_Auth_Owners { get; set; }
        public string CR_Cas_User_Information_Branch_Code { get; set; }
        public Nullable<decimal> CR_Cas_User_Information_Balance { get; set; }
        public string CR_Cas_User_Information_Ar_Name { get; set; }
        public string CR_Cas_User_Information_En_Name { get; set; }
        public string CR_Cas_User_Information_Fr_Name { get; set; }
        public string CR_Cas_User_Information_Mobile { get; set; }
        public string CR_Cas_User_Information_Signature { get; set; }
        public string CR_Cas_User_Information_Image { get; set; }
        public string CR_Cas_User_Information_Emaile { get; set; }
        public string CR_Cas_User_Information_Status { get; set; }
        public string CR_Cas_User_Information_Reasons { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Account_Receipt> CR_Cas_Account_Receipt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Account_Restrictions> CR_Cas_Account_Restrictions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_User_Branch_Validity> CR_Cas_User_Branch_Validity { get; set; }
        public virtual CR_Mas_Com_Lessor CR_Mas_Com_Lessor { get; set; }
        public virtual CR_Cas_User_Validity_Contract CR_Cas_User_Validity_Contract { get; set; }
    }
}
