//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Cas_Renter_Lessor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_Cas_Renter_Lessor()
        {
            this.CR_Cas_Account_Receipt = new HashSet<CR_Cas_Account_Receipt>();
            this.CR_Cas_Account_Restrictions = new HashSet<CR_Cas_Account_Restrictions>();
            this.CR_Cas_Account_Transfers_Tenants = new HashSet<CR_Cas_Account_Transfers_Tenants>();
        }
    
        public string CR_Cas_Renter_Lessor_Id { get; set; }
        public string CR_Cas_Renter_Lessor_Code { get; set; }
        public string CR_Cas_Renter_Lessor_Sector { get; set; }
        public Nullable<System.DateTime> CR_Cas_Renter_Lessor_Date_First_Interaction { get; set; }
        public Nullable<System.DateTime> CR_Cas_Renter_Lessor_Date_Last_Interaction { get; set; }
        public Nullable<int> CR_Cas_Renter_Lessor_Contract_Number { get; set; }
        public Nullable<int> CR_Cas_Renter_Lessor_Days { get; set; }
        public Nullable<decimal> CR_Cas_Renter_Lessor_Interaction_Amount_Value { get; set; }
        public Nullable<int> CR_Cas_Renter_Lessor_KM { get; set; }
        public Nullable<decimal> CR_Cas_Renter_Lessor_Balance { get; set; }
        public Nullable<decimal> CR_Cas_Renter_Rating { get; set; }
        public string CR_Cas_Renter_Membership_Code { get; set; }
        public string CR_Cas_Renter_Admin_Membership_Code { get; set; }
        public string CR_Cas_Renter_Lessor_Status { get; set; }
        public string CR_Cas_Renter_Lessor_Reasons { get; set; }
        public string CR_Cas_Renter_Lessor_Statistics_Nationalities { get; set; }
        public string CR_Cas_Renter_Lessor_Statistics_Country { get; set; }
        public string CR_Cas_Renter_Lessor_Statistics_Gender { get; set; }
        public string CR_Cas_Renter_Lessor_Statistics_Jobs { get; set; }
        public string CR_Cas_Renter_Lessor_Statistics_Regions { get; set; }
        public string CR_Cas_Renter_Lessor_Statistics_City { get; set; }
        public Nullable<int> CR_Cas_Renter_Lessor_Statistics_Age { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Account_Receipt> CR_Cas_Account_Receipt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Account_Restrictions> CR_Cas_Account_Restrictions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Account_Transfers_Tenants> CR_Cas_Account_Transfers_Tenants { get; set; }
        public virtual CR_Mas_Com_Lessor CR_Mas_Com_Lessor { get; set; }
        public virtual CR_Mas_Renter_Information CR_Mas_Renter_Information { get; set; }
    }
}
