//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_ELM_Address
    {
        public string CR_ELM_Ad_Code { get; set; }
        public string CR_ELM_Ad_Ar_Area { get; set; }
        public string CR_ELM_Ad_Ar_City { get; set; }
        public string CR_ELM_Ad_Ar_District { get; set; }
        public string CR_ELM_Ad_EN_District { get; set; }
        public string CR_ELM_Ad_Ar_Street { get; set; }
        public string CR_ELM_Ad_En_Street { get; set; }
        public Nullable<int> CR_ELM_Ad_Bld_No { get; set; }
        public string CR_ELM_Ad_Unit_No { get; set; }
        public string CR_ELM_Ad_Zip_Code { get; set; }
        public string CR_ELM_Ad_Extra_No { get; set; }
    }
}
