//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Elm_Personal
    {
        public string CR_Elm_ID { get; set; }
        public string CR_Elm_Ar_Name { get; set; }
        public string CR_Elm_En_Name { get; set; }
        public string CR_Elm_Sector { get; set; }
        public Nullable<System.DateTime> CR_Elm_BirthDate { get; set; }
        public Nullable<System.DateTime> CR_Elm_Issue_ID_Date { get; set; }
        public Nullable<System.DateTime> CR_Elm_Expiry_ID_Date { get; set; }
        public Nullable<System.DateTime> CR_Elm_Expiry_Driver_Date { get; set; }
        public string CR_Elm_Ar_Nationality { get; set; }
        public string CR_Elm_Ar_Gender { get; set; }
        public string CR_Elm_Ar_Jobs { get; set; }
        public string CR_Elm_Ar_Workplace_Subscription { get; set; }
        public string CR_Elm_Mobile { get; set; }
        public string CR_Elm_Email { get; set; }
        public string CR_Elm_Ar_Social { get; set; }
        public string CR_Elm_Ar_Educational_Qualification { get; set; }
    }
}
