//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Com_Lessor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_Mas_Com_Lessor()
        {
            this.CR_Cas_Account_Pay_Owed = new HashSet<CR_Cas_Account_Pay_Owed>();
            this.CR_Cas_Account_Transfers_Tenants = new HashSet<CR_Cas_Account_Transfers_Tenants>();
            this.CR_Cas_Car_Price_Basic = new HashSet<CR_Cas_Car_Price_Basic>();
            this.CR_Cas_Company_Contract = new HashSet<CR_Cas_Company_Contract>();
            this.CR_Cas_Contract_Basic = new HashSet<CR_Cas_Contract_Basic>();
            this.CR_Cas_Renter_Lessor = new HashSet<CR_Cas_Renter_Lessor>();
            this.CR_Cas_Sup_Bank = new HashSet<CR_Cas_Sup_Bank>();
            this.CR_Cas_Sup_Beneficiary = new HashSet<CR_Cas_Sup_Beneficiary>();
            this.CR_Cas_Sup_Branch = new HashSet<CR_Cas_Sup_Branch>();
            this.CR_Cas_Sup_Car_Information = new HashSet<CR_Cas_Sup_Car_Information>();
            this.CR_Cas_Sup_Features = new HashSet<CR_Cas_Sup_Features>();
            this.CR_Cas_Sup_Follow_Up_Mechanism = new HashSet<CR_Cas_Sup_Follow_Up_Mechanism>();
            this.CR_Cas_Sup_Main_Com_Account = new HashSet<CR_Cas_Sup_Main_Com_Account>();
            this.CR_Cas_Sup_Membership_Conditions = new HashSet<CR_Cas_Sup_Membership_Conditions>();
            this.CR_Cas_Sup_Owners = new HashSet<CR_Cas_Sup_Owners>();
            this.CR_Cas_Sup_SalesPoint = new HashSet<CR_Cas_Sup_SalesPoint>();
            this.CR_Cas_Sup_Sub_Com_Account = new HashSet<CR_Cas_Sup_Sub_Com_Account>();
            this.CR_Cas_User_Information = new HashSet<CR_Cas_User_Information>();
            this.CR_Mas_Basic_Contract = new HashSet<CR_Mas_Basic_Contract>();
            this.CR_Mas_Com_Supporting = new HashSet<CR_Mas_Com_Supporting>();
        }
    
        public string CR_Mas_Com_Lessor_Code { get; set; }
        public string CR_Mas_Com_Lessor_Ar_Long_Name { get; set; }
        public string CR_Mas_Com_Lessor_Ar_Short_Name { get; set; }
        public string CR_Mas_Com_Lessor_En_Long_Name { get; set; }
        public string CR_Mas_Com_Lessor_En_Short_Name { get; set; }
        public string CR_Mas_Com_Lessor_Fr_Long_Name { get; set; }
        public string CR_Mas_Com_Lessor_Fr_Short_Name { get; set; }
        public string CR_Mas_Com_Lessor_Location_Coordinates { get; set; }
        public string CR_Mas_Com_Lessor_Commercial_Registration_No { get; set; }
        public string CR_Mas_Com_Lessor_Sector { get; set; }
        public string CR_Mas_Com_Lessor_Government_No { get; set; }
        public string CR_Mas_Com_Lessor_Tax_Number { get; set; }
        public string CR_Mas_Com_Lessor_Communication_Ar_Officer_Name { get; set; }
        public string CR_Mas_Com_Lessor_Communication_En_Officer_Name { get; set; }
        public string CR_Mas_Com_Lessor_Communication_Fr_Officer_Name { get; set; }
        public string CR_Mas_Com_Lessor_Communication_Officer_Emaile { get; set; }
        public string CR_Mas_Com_Lessor_Communication_Officer_Mobile { get; set; }
        public string CR_Mas_Com_Lessor_Tolk_Free { get; set; }
        public string CR_Mas_Com_Lessor_Email { get; set; }
        public string CR_Mas_Com_Lessor_Twiter { get; set; }
        public string CR_Mas_Com_Lessor_FaceBook { get; set; }
        public string CR_Mas_Com_Lessor_Instagram { get; set; }
        public string CR_Mas_Com_Lessor_Signature_Ar_Director_Name { get; set; }
        public string CR_Mas_Com_Lessor_Signature_En_Director_Name { get; set; }
        public string CR_Mas_Com_Lessor_Signature_Fr_Director_Name { get; set; }
        public string CR_Mas_Com_Lessor_Logo { get; set; }
        public string CR_Mas_Com_Lessor_Logo_Print { get; set; }
        public string CR_Mas_Com_Lessor_Stamp { get; set; }
        public string CR_Mas_Com_Lessor_Signature_Director { get; set; }
        public string CR_Mas_Com_Lessor_Contract_Card { get; set; }
        public string CR_Mas_Com_Lessor_Contract_Conditions { get; set; }
        public string CR_Mas_Com_Lessor_Contract_Conditions_No2 { get; set; }
        public string CR_Mas_Com_Lessor_Status { get; set; }
        public string CR_Mas_Com_Lessor_Reasons { get; set; }
        public string CR_Mas_Com_Lessor_Ar_Ranking { get; set; }
        public string CR_Mas_Com_Lessor_En_Ranking { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Account_Pay_Owed> CR_Cas_Account_Pay_Owed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Account_Transfers_Tenants> CR_Cas_Account_Transfers_Tenants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Car_Price_Basic> CR_Cas_Car_Price_Basic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Company_Contract> CR_Cas_Company_Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Contract_Basic> CR_Cas_Contract_Basic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Renter_Lessor> CR_Cas_Renter_Lessor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Sup_Bank> CR_Cas_Sup_Bank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Sup_Beneficiary> CR_Cas_Sup_Beneficiary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Sup_Branch> CR_Cas_Sup_Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Sup_Car_Information> CR_Cas_Sup_Car_Information { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Sup_Features> CR_Cas_Sup_Features { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Sup_Follow_Up_Mechanism> CR_Cas_Sup_Follow_Up_Mechanism { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Sup_Main_Com_Account> CR_Cas_Sup_Main_Com_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Sup_Membership_Conditions> CR_Cas_Sup_Membership_Conditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Sup_Owners> CR_Cas_Sup_Owners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Sup_SalesPoint> CR_Cas_Sup_SalesPoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Sup_Sub_Com_Account> CR_Cas_Sup_Sub_Com_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_User_Information> CR_Cas_User_Information { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Mas_Basic_Contract> CR_Mas_Basic_Contract { get; set; }
        public virtual CR_Mas_Sup_Sector CR_Mas_Sup_Sector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Mas_Com_Supporting> CR_Mas_Com_Supporting { get; set; }
    }
}
