//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Service_Bnan_Contract
    {
        public string CR_Mas_Service_Bnan_Contract_No { get; set; }
        public string CR_Mas_Service_Bnan_Contract_Code { get; set; }
        public Nullable<decimal> CR_Mas_Service_Bnan_Contract_Price { get; set; }
        public Nullable<bool> CR_Mas_Service_Bnan_Contract_Price_Or_Percentage { get; set; }
        public Nullable<decimal> CR_Mas_Service_Bnan_Contract_Value { get; set; }
        public Nullable<decimal> CR_Mas_Service_Bnan_Contract_Percentage { get; set; }
    }
}
