//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sup_Sub_Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_Mas_Sup_Sub_Account()
        {
            this.CR_Cas_Sup_Sub_Brn_Account = new HashSet<CR_Cas_Sup_Sub_Brn_Account>();
            this.CR_Cas_Sup_Sub_Com_Account = new HashSet<CR_Cas_Sup_Sub_Com_Account>();
        }
    
        public string CR_Mas_Sup_Sub_Account_Code { get; set; }
        public string CR_Mas_Sup_Sub_Account_Main_Code { get; set; }
        public string CR_Mas_Sup_Sub_Account_Ar_Name { get; set; }
        public string CR_Mas_Sup_Sub_Account_En_Name { get; set; }
        public string CR_Mas_Sup_Sub_Account_Status { get; set; }
        public string CR_Mas_Sup_Sub_Account_Reasons { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Sup_Sub_Brn_Account> CR_Cas_Sup_Sub_Brn_Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Sup_Sub_Com_Account> CR_Cas_Sup_Sub_Com_Account { get; set; }
        public virtual CR_Mas_Sup_Main_Account CR_Mas_Sup_Main_Account { get; set; }
    }
}
