//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sup_Category_Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_Mas_Sup_Category_Car()
        {
            this.CR_Cas_Sup_Car_Information = new HashSet<CR_Cas_Sup_Car_Information>();
        }
    
        public string CR_Mas_Sup_Category_Model_Code { get; set; }
        public int CR_Mas_Sup_Category_Car_Year { get; set; }
        public string CR_Mas_Sup_Category_Car_Code { get; set; }
        public Nullable<int> CR_Mas_Sup_Category_Car_Door_No { get; set; }
        public Nullable<int> CR_Mas_Sup_Category_Car_Bag_Bags { get; set; }
        public Nullable<int> CR_Mas_Sup_Category_Car_Small_Bags { get; set; }
        public Nullable<int> CR_Mas_Sup_Category_Car_Passengers_No { get; set; }
        public string CR_Mas_Sup_Category_Car_Picture { get; set; }
        public string CR_Mas_Sup_Category_Car_Status { get; set; }
        public string CR_Mas_Sup_Category_Car_Reasons { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Sup_Car_Information> CR_Cas_Sup_Car_Information { get; set; }
        public virtual CR_Mas_Sup_Category CR_Mas_Sup_Category { get; set; }
        public virtual CR_Mas_Sup_Model CR_Mas_Sup_Model { get; set; }
    }
}
