//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sup_Sector
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_Mas_Sup_Sector()
        {
            this.CR_Cas_Car_Price_Basic = new HashSet<CR_Cas_Car_Price_Basic>();
            this.CR_Cas_Company_Contract = new HashSet<CR_Cas_Company_Contract>();
            this.CR_Cas_Contract_Basic = new HashSet<CR_Cas_Contract_Basic>();
            this.CR_Mas_Basic_Contract = new HashSet<CR_Mas_Basic_Contract>();
            this.CR_Mas_Com_Lessor = new HashSet<CR_Mas_Com_Lessor>();
            this.CR_Mas_Renter_Information = new HashSet<CR_Mas_Renter_Information>();
            this.CR_Mas_Sup_Employer = new HashSet<CR_Mas_Sup_Employer>();
        }
    
        public string CR_Mas_Sup_Sector_Code { get; set; }
        public string CR_Mas_Sup_Sector_Address_Code { get; set; }
        public string CR_Mas_Sup_Sector_Ar_Name { get; set; }
        public string CR_Mas_Sup_Sector_En_Name { get; set; }
        public string CR_Mas_Sup_Sector_Fr_Name { get; set; }
        public string CR_Mas_Sup_Sector_Status { get; set; }
        public string CR_Mas_Sup_Sector_Reasons { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Car_Price_Basic> CR_Cas_Car_Price_Basic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Company_Contract> CR_Cas_Company_Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Contract_Basic> CR_Cas_Contract_Basic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Mas_Basic_Contract> CR_Mas_Basic_Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Mas_Com_Lessor> CR_Mas_Com_Lessor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Mas_Renter_Information> CR_Mas_Renter_Information { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Mas_Sup_Employer> CR_Mas_Sup_Employer { get; set; }
    }
}
