//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sup_Payment_Method
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_Mas_Sup_Payment_Method()
        {
            this.CR_Cas_Account_Receipt = new HashSet<CR_Cas_Account_Receipt>();
        }
    
        public string CR_Mas_Sup_Payment_Method_Code { get; set; }
        public string CR_Mas_Sup_Payment_Method_Type { get; set; }
        public string CR_Mas_Sup_Payment_Method_Ar_Name { get; set; }
        public string CR_Mas_Sup_Payment_Method_En_Name { get; set; }
        public string CR_Mas_Sup_Payment_Method_Status { get; set; }
        public string CR_Mas_Sup_Payment_Method_Reasons { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Account_Receipt> CR_Cas_Account_Receipt { get; set; }
    }
}
