//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sup_Bank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_Mas_Sup_Bank()
        {
            this.CR_Cas_Sup_Bank = new HashSet<CR_Cas_Sup_Bank>();
        }
    
        public string CR_Mas_Sup_Bank_Code { get; set; }
        public string CR_Mas_Sup_Bank_Ar_Name { get; set; }
        public string CR_Mas_Sup_Bank_En_Name { get; set; }
        public string CR_Mas_Sup_Bank_Status { get; set; }
        public string CR_Mas_Sup_Bank_Reasons { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Cas_Sup_Bank> CR_Cas_Sup_Bank { get; set; }
    }
}
