//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sup_City
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CR_Mas_Sup_City()
        {
            this.CR_Mas_Address = new HashSet<CR_Mas_Address>();
            this.CR_MAS_Renter_Addre = new HashSet<CR_MAS_Renter_Addre>();
        }
    
        public string CR_Mas_Sup_City_Code { get; set; }
        public string CR_Mas_Sup_City_Group_Code { get; set; }
        public string CR_Mas_Sup_City_Regions_Code { get; set; }
        public string CR_Mas_Sup_City_Ar_Name { get; set; }
        public string CR_Mas_Sup_City_En_Name { get; set; }
        public string CR_Mas_Sup_City_Fr_Name { get; set; }
        public string CR_Mas_Sup_City_Location_Coordinates { get; set; }
        public Nullable<int> CR_Mas_Sup_City_Counter { get; set; }
        public string CR_Mas_Sup_City_Status { get; set; }
        public string CR_Mas_Sup_City_Reasons { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_Mas_Address> CR_Mas_Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_MAS_Renter_Addre> CR_MAS_Renter_Addre { get; set; }
        public virtual CR_Mas_Sup_Group CR_Mas_Sup_Group { get; set; }
        public virtual CR_Mas_Sup_Regions CR_Mas_Sup_Regions { get; set; }
    }
}
