//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sup_Service_Fee_Tga
    {
        public string CR_Mas_Sup_Service_Fee_Tga_Code { get; set; }
        public string CR_Mas_Sup_Service_Fee_Tga_Ar_Name { get; set; }
        public string CR_Mas_Sup_Service_Fee_Tga_En_Name { get; set; }
        public Nullable<decimal> CR_Mas_Sup_Service_Fee_Tga_Value { get; set; }
        public string CR_Mas_Sup_Service_Fee_Tga_Status { get; set; }
        public string CR_Mas_Sup_Service_Fee_Tga_Resons { get; set; }
    }
}
