//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CR_Mas_Sup_Service_Fee_Bnan
    {
        public string CR_Mas_Sup_Service_Fee_Bnan_Code { get; set; }
        public Nullable<int> CR_Mas_Sup_Service_Fee_Bnan_Price { get; set; }
        public string CR_Mas_Sup_Service_Fee_Bnan_Ar_Name { get; set; }
        public string CR_Mas_Sup_Service_Fee_Bnan_En_Name { get; set; }
        public string CR_Mas_Sup_Service_Fee_Bnan_Fr_Name { get; set; }
        public Nullable<decimal> CR_Mas_Sup_Service_Fee_Bnan_Percentage { get; set; }
        public Nullable<decimal> CR_Mas_Sup_Service_Fee_Bnan_Value { get; set; }
        public string CR_Mas_Sup_Service_Fee_Bnan_Status { get; set; }
        public string CR_Mas_Sup_Service_Fee_Bnan_Resons { get; set; }
    }
}
